### ISSUE TITLE
Really good 

### ISSUE THREAD

**Issue by ETeissonniere** [RobinDavid/pystack#2]
Hello, I found pystack  really good, maybe I will  make tor-like with it and a tool to prevent port scans.
Maybe we will can add them to examples right? 
I will be very happy if I can help you.

**Comment by RobinDavid** [comment]
Hi there,
Nice, that would be great. I don't know if pystack is stable enough for a tor-like but it worth giving it a try. Sure I can add them to examples. Don't hesitate making a pull request :wink:
